name: Extension uploader
on:
  push:
    tags:
    - '*'
  workflow_dispatch: {}
jobs:
  upload_plz_thx:
    name: Uploader
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ./actions/uploader/
      uses: ./actions/uploader/
      env:
        USERNAME: ${{ secrets.GNOME_USERNAME }}
        PASSWORD: ${{ secrets.GNOME_PASSWORD }}
    - name: Archive extension zipball
      uses: actions/upload-artifact@v2
      with:
        name: zipball
        path: dist/system-monitor-next@paradoxxx.zero.gmail.com.zip
